### ISSUE TITLE
Ascendence: Visual bugs

### ISSUE THREAD

**Issue by jenes2** [EasyRPG/Player#1293]
#### Name of the game:
Ascendence RSD VI - https://rpgmaker.net/games/736/downloads/

#### Player platform:
Windows (32 bit) - Continuous build

#### Attach files
![save](https://user-images.githubusercontent.com/33015808/31872558-4e80504e-b800-11e7-85c9-283ecbc8ab62.gif)

#### Issues:
- [X] Slight animation bugs in intro for characters Kell and Velto (pulling animation, walking headbob hair) (**fixed in #1601 for 0.6.1**)
- [X] City intro fade-in is too quick compared to original
- [x] Screen shake for first elevator is not emulated (**fixed in 0.6**)
- [X] Strange red box around player when entering/leaving save zone (see gif)

**Comment by fdelapena** [comment]
Hi, thanks for the report.

The red box issue is possibly related with #1225.

**Comment by Albeleon** [comment]
"City intro fade-in is too quick compared to original"
Test if #1369 or #1397 fixed this.

Strange red box around player when entering/leaving save zone (see gif)
Test it #1380 fixed this.

**Comment by wew1234** [comment]
Sorry for the delay, forgot my original account details. Tried the latest release from `https://easyrpg.org/player/downloads/`.

Fixed
- City intro fade-in is too quick compared to original
- Strange red box around player when entering/leaving save zone

Still occurring
- Slight animation bugs in intro for characters Kell and Velto (pulling animation, walking headbob hair)
- Screen shake for first elevator is not emulated

Thank you!

**Comment by carstene1ns** [comment]
Thanks, I have updated the original issue comment with this information. :+1:

**Comment by fmatthew5876** [comment]
Shake screen issue should be fixed by #1548

**Comment by wew1234** [comment]
Tried the latest release from https://easyrpg.org/player/downloads/.

Fixed

* Elevator shake, but screen sides are not the correct color (should be black)
![elevator easyrpg](https://user-images.githubusercontent.com/36687735/51414206-7af67900-1b69-11e9-8dc1-9b66bf701e0c.gif)
![elevator rpgmaker](https://user-images.githubusercontent.com/36687735/51414207-7af67900-1b69-11e9-951d-d42f3bc53cad.gif)

Still occurring
* Slight animation bugs in intro for characters Kell and Velto (pulling animation, walking headbob hair)
![pull animation](https://user-images.githubusercontent.com/36687735/51414251-aa0cea80-1b69-11e9-965a-ce83995ab121.gif) ![hair animation](https://user-images.githubusercontent.com/36687735/51414252-aa0cea80-1b69-11e9-8e38-2dc547d9a6ef.gif)

Thank you!

**Comment by Ghabry** [comment]
the remaining issues are maybe fixed by #1601, needs test

**Comment by wew1234** [comment]
Tried the latest continuous build from https://easyrpg.org/player/downloads/

Still occurring
* Slight animation bugs in intro for characters Kell and Velto
![pulling](https://user-images.githubusercontent.com/36687735/52988436-37f12500-33f7-11e9-81fd-49d2aabd385d.gif) ![walking](https://user-images.githubusercontent.com/36687735/52988437-37f12500-33f7-11e9-81a7-5b3eeadb832c.gif)

**Comment by fdelapena** [comment]
@wew1234 thank you for the feedback! Please try animations with the following special build:
https://ci.easyrpg.org/view/Pull%20Requests/job/player-win32-pr/2470/artifact/bin/easyrpg_windows.zip

**Comment by carstene1ns** [comment]
This seems to be the same glitch like the red haired girl in A*(what was the name again?) intro, which is also only half fixed.

**Comment by wew1234** [comment]
The animation glitch appears to be fixed, Thank you!

This is some comparisons - top is EasyRPG, bottom is RPGMaker
* Pulling
![pulling](https://user-images.githubusercontent.com/36687735/53008245-de0d5100-3430-11e9-9561-b48127fb4363.gif)
![pulling](https://user-images.githubusercontent.com/36687735/53008253-e36a9b80-3430-11e9-8d31-a3147482d9c7.gif)
* Walking
![walking](https://user-images.githubusercontent.com/36687735/53008301-fe3d1000-3430-11e9-8073-477636c7b7e1.gif)
![walking](https://user-images.githubusercontent.com/36687735/53008311-02692d80-3431-11e9-87a4-1ac9cdc2655e.gif)
* Elevator
![elevator](https://user-images.githubusercontent.com/36687735/53008333-0ac16880-3431-11e9-8bb3-d3cc1c9f55f2.gif)
![elevator](https://user-images.githubusercontent.com/36687735/53008357-19a81b00-3431-11e9-84bb-53409c4ba61d.gif)
* Saving
![saving](https://user-images.githubusercontent.com/36687735/53008376-29276400-3431-11e9-94cd-20a269298619.gif)
![save](https://user-images.githubusercontent.com/36687735/53008380-2c225480-3431-11e9-943d-6acf0f505244.gif)

**Comment by Ghabry** [comment]
okay then this will be resolved as part of 0.6.1. thanks for testing.
