### ISSUE TITLE
Improper cleanup when returning to the title screen

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Player#1524]
At least it seems the https://easyrpg.org/play/master/?game=tdf2018wildcompodemo&new-game misbehaves on restart, lacks some stuff, e.g. the first scene and missing the rotating "cube".

- [x] Proper cleanup when ``--new-game`` is used with F12
- [x] Proper cleanup after Game Over (See https://community.easyrpg.org/t/not-sure-if-this-has-been-documented-before/707/1)
- [x] Proper cleanup after End Game

**Comment by fmatthew5876** [comment]
Probably load game is broken in similar ways.

We should be using RAII to automatically clean up stuff.

**Comment by Ghabry** [comment]
This could be related to the awful "Game_Temp::restart_title_flag" invented by Sormat whose only purpose is to prevent a Reinitialisation (and BGM restart) when returning from Load to Title via Cancel button.

Maybe the flag is not set to "true" in all code paths.

That whole restart-title-junk should be refactored, already hated it when it was added.

**Comment by Ghabry** [comment]
The problem here isn't the lack of cleanup but that the BGM is not stopped therefore the game reads the wrong value in the first frame of the game. ^^'

**Comment by Ghabry** [comment]
hm, no, there is also another problem... sorry. Now I see it.

**Comment by Ghabry** [comment]
@fdelapena 
Can't find the PR but iirc I fixed this via https://github.com/EasyRPG/Player/commit/8e88e081d3d18bba8d9169cc85ddf9f0c2fcbcb2
Was there anything left?

**Comment by fdelapena** [comment]
Tested with current master and it's still broken but in a different way. Also, when pressing F12 behaves even different.

**Comment by Ghabry** [comment]
Also broken when Game Over happens as documented here: https://community.easyrpg.org/t/not-sure-if-this-has-been-documented-before/707/1

I already had multiple times (though randomly) that the title screen graphic does not appear anymore after pressing F12.

Lets take this issue as a catch-all for any bugs related to teardown.

**Comment by fmatthew5876** [comment]
#2023 might help with this.

**Comment by fdelapena** [comment]
Played tdf2018wildcompodemo in recent master, the game works flawlessly now after playing the loop :+1:

**Comment by rueter37** [comment]
If you play a RPG Maker 2003 game and the System2 graphics have been set once (which happens if you enter a RPG Maker 2003 battle) and then you exit the game and start an other RPG Maker 2003 game via the browser the System2 graphics from the first game are still used. This leads even to "checkered" graphics if the System2 filename from the first game doesn't exist in the second game.

**Comment by fdelapena** [comment]
Played affected projects, can't reproduce the issues mentioned anymore. #1578 and #2023 and later #2429 for the system2 issue did the trick. No new reports since a while, so let's consider this as fixed, despite still has margin for design improvements.
