### ISSUE TITLE
Somes bugs on Velsarbor

### ISSUE THREAD

**Issue by FalcoRPGMaker** [EasyRPG/Player#658]
Hello ! 
I tried Velsarbor with Easy RPG, great job the game run almost perfectly, but somes bugs are stillpresents, including a freeze.
- Regular FPS Falls down.
- Often the pictures are displayed offset from where they should be, and replaced after.
- There's a little shift (I don't know if it's the good word in english) on some letters in the dialogues
- Black picture or background in the intro are remplaced by white.
- I had a big freeze at least 8 seconds for the intro, no particular reason.
- At the end of a map I had just a black screen with a small musical seconds that turned repeatedly.
  As if the game could not hang the next scene

Good luck !

**Comment by BlisterBoy** [comment]
Hi falco ^^. Thanks for the report !

Versarbor:
German (original version): 
http://rpgmaker.net/articles/763/

French (version):
http://www.rpg-maker.fr/dl/monos/jeu/Velsarborfr.rar

I suppose Falco played the french version, but they should be identical !

**Comment by carstene1ns** [comment]
I can confirm the placement bugs, seems like the horizontal offset is wrong for the animations.
Here is a demo video: http://p.f4ke.de/z6RcJJEymw.webm

The white backgrounds are because some black images are displayed with 100% transparency, so if the background beyond them is white, it looks like this. No idea if we draw the background in the wrong colour or if this is some quirk rpg_rt has.

However, i encountered no long freeze in the intro, it runs smooth.

**Comment by Ghabry** [comment]
@FalcoRPGMaker 
Could you recheck this?

**Comment by BlisterBoy** [comment]
I've tested the introduction cut scene, there is a lot of offset picture problem, as the one described by carstene. I didn't noticed any FPS drop.

**Comment by Ghabry** [comment]
This needs a recheck bc battleanimations got fixed

**Comment by Medhoc** [comment]
There is less visual glitches but the intro always look like on the carstene's video :(.

**Comment by Ghabry** [comment]
@BlisterB 
Is Velsarbor fixed in the meanwhile?

**Comment by carstene1ns** [comment]
The visual glitches are still present, but i did not encounter freezes or fps drops yet (and never did before, but not played much either<.<).

---

Let's take the scene with the red haired woman for example:
![glitches](https://picload.org/image/rdgiidgd/velsarbor3.gif)
(gif is cut to skip the dialogue in-between)

**Begin of scene**
![begin](https://picload.org/image/rdgiirdo/1473959974.png)

**End of scene**
![end](https://picload.org/image/rdgiirdc/1473960052.png)

**Comment by BlisterB** [comment]
I've played the most part of the french demo, and I didn't see one fps drop. Just the visual gliths shown by Carstene.

(Sorry Ghabry, I wasn't able to test the game when I saw your post, and I've totally forgot it. :S)

**Comment by Ghabry** [comment]
@carstene1ns  confirmed that the patch provided for #1114 fixes the last issue reported here 🎊 🎉
